"""add check_in_time and check_out_time to attendance

Revision ID: a2a373e6bfe1
Revises: 2dcf93cc78b7
Create Date: 2026-04-19 07:13:18.899807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2a373e6bfe1'
down_revision = '2dcf93cc78b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('check_in')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('check_out')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_out', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('check_in', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')

    # ### end Alembic commands ###
