"""add full_name to members

Revision ID: ddbfef005562
Revises: e47194a169c1
Create Date: 2026-04-18 13:39:38.719790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddbfef005562'
down_revision = 'e47194a169c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_constraint('members_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('joined_at')
        batch_op.drop_column('emergency_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('joined_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('members_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('gender')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
